<?php
$_API_URL_USAPPY = 'http://usappy.com/api/';
$_API_URL_UPS = 'http://verify-ups.com/api/';
$_API_SECRET = 'sec';

if (YII_ENV == 'prod') {
    $_API_URL_USAPPY = 'https://usappy.jp/api/';
    $_API_URL_UPS = 'https://usami-p.com/api/';
    $_API_SECRET = 'CJCHG2SEFN';
}

return [
    'api' => [
        'ss' => [
            'url_ss' => $_API_URL_USAPPY . 'ss',
        ],
        'car' => [
            'url_car' => $_API_URL_USAPPY . 'car',
            'url_card_info' => $_API_URL_UPS . 'getmembercard',
            'url_car_info' => $_API_URL_UPS . 'getmembercar',
            'url_update_member_car' => $_API_URL_UPS . 'updmembercar',
            'url_update_member_card' => $_API_URL_UPS . 'updmembercard',
        ],
        'member' => [
            'url_card' => $_API_URL_UPS . 'getcardno',
            'url_member' => $_API_URL_UPS . 'getmemberbasic',
            'url_member_list' => $_API_URL_UPS . 'getmembers',
            'url_update_member' => $_API_URL_UPS . 'updmemberbasic',
        ],
        'zipcode' => [
            'url_addr' => $_API_URL_USAPPY . 'zipcode'
        ],
        'secret' => $_API_SECRET,
    ],
    'd02SyakenCycle' => [
        '1' => '1',
        '2' => '2',
    ],
    'd03YoyakuSagyoNo' => [
        '0' => '',
        '1' => 'タイヤ',
        '2' => 'オイル',
        '3' => 'バッテリー',
        '4' => 'コーティング',
        '5' => 'リペア',
        '6' => '車検',
        '7' => 'その他',
    ],
    'D03_TANTO_SEIｏD03_TANTO_MEI' => [

    ],
    'M05_COM_CD_TAISA' => range(42000, 42999),
    'adminEmail' => 'admin@example.com',
    'defaultPageSize' => '20',
    'message_save_error' => '保存が失敗しました。',
    'status' => [
        '' => '指定なし',
        '0' => '受付データ',
        '1' => '予約データ',
        '2' => '作業確定',
    ],
    'timeOutLogin' => 1800,
    'zippdf' => [
        'year' => [
            '2016' => '2016',
            '2017' => '2017',
            '2018' => '2018',
            '2019' => '2019',
            '2020' => '2020',
            '2021' => '2021',
            '2022' => '2022',
            '2023' => '2023',
            '2024' => '2024',
        ],
        'month' => [
            '01' => '01',
            '02' => '02',
            '03' => '03',
            '04' => '04',
            '05' => '05',
            '06' => '06',
            '07' => '07',
            '08' => '08',
            '09' => '09',
            '10' => '10',
            '11' => '11',
            '12' => '12'
        ],
        'day' => [
            '01' => '01',
            '02' => '02',
            '03' => '03',
            '04' => '04',
            '05' => '05',
            '06' => '06',
            '07' => '07',
            '08' => '08',
            '09' => '09',
            '10' => '10',
            '11' => '11',
            '12' => '12',
            '13' => '13',
            '14' => '14',
            '15' => '15',
            '16' => '16',
            '17' => '17',
            '18' => '18',
            '19' => '19',
            '20' => '20',
            '21' => '21',
            '22' => '22',
            '23' => '23',
            '24' => '24',
            '25' => '25',
            '26' => '26',
            '27' => '27',
            '28' => '28',
            '29' => '29',
            '30' => '30',
            '31' => '31',
        ]
    ],
    'vat' => 0,
    'route_keep_cookie' => [
        'usappynumberchange/default/index',
        'usappynumberchange/default/confirm',
        'usappynumberchange/default/complete',
        'registworkslip/default/index'
    ],
    'admin_user' => [
        '0' => [
            'ssid' => 'fcc',
            'password' => 'npaZd3Ec'
        ],
        '1' => [
            'ssid' => 'dom',
            'password' => 'x3Y4x55p89kz'
        ]
    ],
    'branch' => [
        '202480' => '東日本宇佐美　北海道支店',
        '283963' => '東日本宇佐美　東北支店',
        '326855' => '東日本宇佐美　上信越支店',
        '458926' => '東日本宇佐美　東京販売支店',
        '458935' => '東日本宇佐美　神奈川販売支店',
        '458944' => '東日本宇佐美　埼玉栃木販売支店',
        '458953' => '東日本宇佐美　千葉茨城販売支店',
        '451987' => '西日本宇佐美　東海支店',
        '457142' => '西日本宇佐美　中部支店',
        '513545' => '西日本宇佐美　北陸支店',
        '575167' => '西日本宇佐美　関西支店',
        '603074' => '西日本宇佐美　山陽支店',
        '784351' => '西日本宇佐美　九州支店',
        '458720' => 'ダイツー',
    ],
    'sateiss' => [
        '325106',
        '317437',
        '280715',
        // '332152', 未稼働
    ],
	'items' => [
				'BS' => [
					"REGNO　GR-XI",
					"REGNO　GR-XT",
					"REGNO　GRVⅡ",
					"REGNO　GRV",
					"REGNO　ＧＲ-Ｌｅｇｇｅｒａ",
					"POTENZA　RE-71R",
					"POTENZA　RE-11《RE-01R》",
					"POTENZA　S001【RE050】",
					"POTENZA　AdrenalinRE003",
					"POTENZA　AdrenalinRE002",
					"POTENZA　RE-11A{RE－11A　3.3T}",
					"POTENZA　　　A)RE-11A『RE-11A 4.0』 B)RE-11《RE-01R》（RE-01）C）RE-05D",
					"POTENZA　RE-11《RE-01R》（RE-01）",
					"POTENZA　S001RFT",
					"Playz　PX",
					"Playz　PX-RV",
					"Playz　PX-C",
					"Playz　PZ-X[PZ-1]<V'GRID>",
					"Playz　PZ-X[PZ-1]",
					"Playz　PZ-XC",
					"Playz　PZ-XC<GⅢ>",
					"Playz　PlayzRVPRV-1 ecopia",
					"ECOPIA　EV-01",
					"ECOPIA　EP100",
					"ECOPIA　EP001S",
					"ECOPIA　EP500 ologic",
					"ECOPIA　PZ-X",
					"ECOPIA　PZ-XC",
					"ECOPIA　PRV",
					"ECOPIA　EX20",
					"ECOPIA　EX20C",
					"ECOPIA　EX20C TYPE-H",
					"ECOPIA　EX20 RV",
					"ECOPIA　EX10",
					"NEXTRY　NEXTRY",
					"NEXTRY　NEXTRY〔SNEAKER SNK2〕",
					"SNEAKER　SNK2≪SNK2 ecopia≫＜Sneaker＞",
					"SNEAKER　SNK2＜Sneaker＞",
					"POTENZA　RE-11S",
					"POTENZA　RE050",
					"POTENZA　　　A)S001B)S007",
					"POTENZA　　　A)RE030B)RE040C)RE71D)RE92A",
					"ECOPIA　EP02",
					"DUELER　　　A)H/L 400B)H/P SPORT",
					"TURANZA　　A)EL42B)ER300C)ER33D)ER42E)T001",
					"A)B250B)B380C)B391",
					"DUELER　H/L850",
					"DUELER　H/L683",
					"DUELER　H/L ALENZA",
					"DUELER　H/P SPORT",
					"DUELER　H/P680",
					"DUELER　A/T694",
					"DUELER　M/T674",
					"DUELER　M/T673",
					"DUELER　H/L400",
					"DUELER　H/L33",
					"DUELER　H/T840",
					"DUELER　H/T689",
					"DUELER　H/T687",
					"DUELER　H/T684",
					"DUELER　H/T470",
					"DUELER　DESERTDUELER604",
					"DUELER　DESERTDUELER610",
					"ECOPIA　R680ﾁｭｰﾌﾞﾚｽ",
					"ECOPIA　605Vﾁｭｰﾌﾞﾚｽ",
					"MRﾁｭｰﾌﾞﾚｽ",
					"ECOPIA　R201ﾁｭｰﾌﾞﾚｽ",
					"ECOPIA　M812ﾁｭｰﾌﾞﾚｽ",
					"V600ﾁｭｰﾌﾞﾚｽ",
					"604Vﾁｭｰﾌﾞﾚｽ",
					"613Vﾁｭｰﾌﾞﾚｽ",
					"650Vﾁｭｰﾌﾞﾚｽ",
					"610Vﾁｭｰﾌﾞﾚｽ",
					"R230ﾁｭｰﾌﾞﾚｽ",
					"G561ﾁｭｰﾌﾞﾚｽ",
					"R202ﾁｭｰﾌﾞﾚｽ",
					"M810ﾁｭｰﾌﾞﾚｽ",
					"M810ﾁｭｰﾌﾞﾀｲﾌﾟ",
					"VLCPﾁｭｰﾌﾞﾀｲﾌﾟ",
					"G590ﾁｭｰﾌﾞﾚｽ",
					"DURAVIS　R670ﾁｭｰﾌﾞﾚｽ",
					"DURAVIS　DURAVIS CAMPERﾁｭｰﾌﾞﾚｽ",
					"AAﾁｭｰﾌﾞﾚｽ",
					"DURAVIS　R205ﾁｭｰﾌﾞﾚｽ",
					"DURAVIS　R205ﾁｭｰﾌﾞﾀｲﾌﾟ",
					"DURAVIS　M804ﾁｭｰﾌﾞﾚｽ",
					"DURAVIS　M804ﾁｭｰﾌﾞﾀｲﾌﾟ",
				],
				'YH' => [
					"ZEN　　903ZW",
					"ZEN　　902ZE",
					"901ZS",
					"SY797",
					"SY297A",
					"SY297",
					"SY397",
					"SY167",
					"SY190",
					"ZEN　　702ZE-i",
					"ZEN　　702ZE",
					"ZEN　　701ZE",
					"TY787T",
					"TY287",
					"TY228",
					"TY517E",
					"MY507A",
					"ZEN　　102ZE",
					"RY237",
					"RY407",
					"RY068",
					"RY437",
					"RY103",
					"RY523",
					"RY357",
					"RY623",
					"MY777",
					"MY247",
					"MY248",
					"MY277A",
					"MY377",
					"LY117A",
					"LY317",
					"BluEarth　　LT152R",
					"LT151R",
					"RY01",
					"RY208",
					"RY206",
					"MY807",
					"LY018",
					"Y765L",
					"TY285",
					"TY228",
					"iceGUARD　　IG91",
					"SY01",
					"NEOVA 　　AD07",
					"NEOVA 　　AD08R",
					"ADVAN 　　A08B",
					"ADVAN 　　V551",
					"ADVAN Sport　　　V103",
					"ADVAN Sport　　　V105",
					"ADVAN Sport　Z･P･S　　V103 ZPS",
					"BluEarth 　　AE01",
					"BluEarth 　　AE01F",
					"BluEarth 　　RV01",
					"BluEarth 　　RV02",
					"BluEarth-1 　　EF20",
					"BluEarth-A 　　AE50",
					"Earth-1　　EP400",
					"ECOS 　　ES300",
					"ECOS 　　ES31",
					"HF Type D　　A008",
					"map 　　ES340",
					"S.drive　　AS01",
					"S208　　S208",
					"ADVAN S.T.　　V802",
					"GEO A/T-S　　G012",
					"GEO H/T　　G056",
					"GEO H/T-S　　G051",
					"GEO M/T+　　G001C",
					"GEO SUV　　G055",
					"PARADA　　PA02",
					"PARADA　　PA03",
					"TAXI　　Y895",
					"GEOLANDAR IT-S　　G072",
					"GEOLANDAR IT-S　　G073",
					"ice GUARD　　IG30PL",
					"ice GUARD　　IG50PL",
					"TAXI　　IGT2",
					"TAXI　　IGT2A",
				],
				'DF' => [
					"AT3",
					"DZ03G",
					"DZ102",
					"DZZ2S",
					"EC201",
					"EC202",
					"EC202L",
					"EC203",
					"ES100",
					"ESLRR",
					"ESNEXT",
					"LM704",
					"LM704AA",
					"MAX050",
					"MAX050+",
					"PT2",
					"PT3",
					"RV504",
					"VE303",
					"DSX2",
					"SJ8",
					"WM01",
					"DV01",
					"ESVN01",
					"MT2",
					"SP185",
					"SP355",
					"SP485",
					"SP495",
					"SPLT33",
					"SPLT38",
					"DSV01",
					"SPLT02",
					"WMLT03",
					"WMSV01",
				],
				'FK' => [
					"SN828",
					"SN832I",
					"ZE914",
					"ZE914EF",
					"EPZ",
					"EPZF",
				],
				'TY' => [
					"NANOENERGY 3 plus",
					"TOYO　V-02e",
					"PROXES　CF2",
					"TOYO J60",
					"TRANPATH LuK",
					"TRANPATH　MPZ",
					"TRANPATH LuⅡ",
					"NANOENERGY 2",
					"NANOENERGY 3",
					"PROXES T1 Sport",
					"ECO WALKER",
					"TRANPATH　Lu",
					"TRANPATH　SU sport",
					"TRANPATH　M/T",
					"TRANPATH　S/U",
					"TRANPATH　A/T",
					"PROXES　T1R",
					"PROXES　C1S",
					"PROXES　S/T",
					"PROXES　R1R",
					"PROXES　R888",
					"TOYO　DRB",
					"TOYO　TEO plus",
					"TOYO　V-02",
					"TOYO　H20",
					"TOYO i　J18",
					"LIZA CLT",
					"TOYO　J60",
					"TOYO i　A06",
					"PROXES C1S spec-a",
					"NANOENERGY 0",
					"PROXES T1 Sport SUV",
					"PROXES　CF2 SUV",
					"DELVEX　M134",
					"DELVEX　M634",
					"M136 ZEROSYS",
					"M131",
					"M614",
					"M133",
					"M637",
					"M319",
					"M501",
					"M323P",
					"M667 ZEROSYS premium",
					"M666 ZEROSYS premium",
					"M636",
					"M626",
					"M620",
					"M614",
					"M166 ZEROSYS",
					"M125",
					"M140",
					"M101",
					"M120",
					"M149",
					"NANOENERGY M638",
					"M139",
					"M666 ZEROSYS",
					"M166 ZEROSYS",
					"M631",
					"M628",
					"M317",
					"M320",
					"M519",
					"M319",
					"M317zp",
					"M504",
					"M505",
					"DELVEX　M934",
					"M917",
					"M929 premium",
					"M966 ZEROSYS",
					"M919",
					"M920",
					"M923",
					"M913",
					"M916",
					"DELVEX 934",
					"OBSERVE GARIT GIZ",
					"OBSERVE GSi-5",
					"Winter TRANPATH　MK4α",
					"GARIT　G5",
					"Winter TRANPATH　S1",
					"GARIT　G30",
					"OBSERVE GARIT SV For Taxi",
				],
			],
    'car_regions' => [
        '北海道・東北' => [
            '北海道' => [
                "函館",
                "北見",
                "室蘭",
                "帯広",
                "旭川",
                "札幌",
                "釧路",
            ],
            '青森県' => [
                "八戸",
                "青森",
            ],
            '岩手県' => [
                "岩手",
                "平泉",
                "盛岡",
            ],
            '宮城県' => [
                "仙台",
                "宮城",
            ],
            '秋田県' => [
                "秋田",
            ],
            '山形県' => [
                "山形",
                "庄内",
            ],
            '福島県' => [
                "いわき",
                "会津",
                "福島",
                "郡山",
            ],
        ],
        '関東' => [
            '茨城県' => [
                "つくば",
                "土浦",
                "水戸",
            ],
            '栃木県' => [
                "とちぎ",
                "宇都宮",
                "那須",
            ],
            '群馬県' => [
                "前橋",
                "群馬",
                "高崎",
            ],
            '埼玉県' => [
                "大宮",
                "川口",
                "川越",
                "所沢",
                "春日部",
                "熊谷",
                "越谷",
            ],
            '千葉県' => [
                "千葉",
                "成田",
                "柏",
                "習志野",
                "袖ヶ浦",
                "野田",
            ],
            '東京都' => [
                "世田谷",
                "八王子",
                "品川",
                "多摩",
                "杉並",
                "練馬",
                "足立",
            ],
            '神奈川県' => [
                "川崎",
                "横浜",
                "湘南",
                "相模",
            ],
        ],
        '中部' => [
            '新潟県' => [
                "新潟",
                "長岡",
            ],
            '富山県' => [
                "富山",
            ],
            '石川県' => [
                "石川",
                "金沢",
            ],
            '福井県' => [
                "福井",
            ],
            '山梨県' => [
                "富士山",
                "山梨",
            ],
            '長野県' => [
                "松本",
                "諏訪",
                "長野",
            ],
            '岐阜県' => [
                "岐阜",
                "飛騨",
            ],
            '静岡県' => [
                "伊豆",
                "富士山",
                "沼津",
                "浜松",
                "静岡",
            ],
            '愛知県' => [
                "一宮",
                "三河",
                "名古屋",
                "尾張小牧",
                "岡崎",
                "春日井",
                "豊橋",
                "豊田",
            ],
        ],
        '近畿' => [
            '三重県' => [
                "三重",
                "鈴鹿",
            ],
            '滋賀県' => [
                "滋賀",
            ],
            '京都府' => [
                "京都",
            ],
            '大阪府' => [
                "なにわ",
                "和泉",
                "堺",
                "大阪",
            ],
            '兵庫県' => [
                "姫路",
                "神戸",
            ],
            '奈良県' => [
                "奈良",
            ],
            '和歌山県' => [
                "和歌山",
            ],
        ],
        '中国・四国' => [
            '鳥取県' => [
                "鳥取",
            ],
            '島根県' => [
                "島根",
            ],
            '岡山県' => [
                "倉敷",
                "岡山",
            ],
            '広島県' => [
                "広島",
                "福山",
            ],
            '山口県' => [
                "下関",
                "山口",
            ],
            '徳島県' => [
                "徳島",
            ],
            '香川県' => [
                "香川",
            ],
            '愛媛県' => [
                "愛媛",
            ],
            '高知県' => [
                "高知",
            ],
        ],
        '九州・沖縄' => [
            '福岡県' => [
                "久留米",
                "北九州",
                "福岡",
                "筑豊",
            ],
            '佐賀県' => [
                "佐賀",
            ],
            '長崎県' => [
                "佐世保",
                "長崎",
            ],
            '熊本県' => [
                "熊本",
            ],
            '大分県' => [
                "大分",
            ],
            '宮崎県' => [
                "宮崎",
            ],
            '鹿児島県' => [
                "奄美",
                "鹿児島",
            ],
            '沖縄県' => [
                "沖縄",
            ],
        ]
     ]
];
